#include <M5Cardputer.h>
#include <M5Unified.h>
#include <M5GFX.h>
#include "wifi_scan.h"
#include "ui_render.h"
#include "keyboard_input.h"
enum AppState { STATE_SCANNING, STATE_LIST, STATE_MEASURING };
struct AppStateData { AppState current_state = STATE_SCANNING; AppState next_state = STATE_SCANNING; uint16_t selected_ap_index = 0; uint32_t last_scan_time = 0; uint32_t last_measure_time = 0; int16_t rssi_history[30] = {}; uint8_t rssi_history_count = 0; } app_state;
WiFiScanResult wifi_networks[MAX_NETWORKS];
uint16_t network_count = 0;
void setup() { auto cfg = M5.config(); M5Cardputer.begin(cfg, true); M5Cardputer.Display.setRotation(1); WiFi.mode(WIFI_STA); WiFi.disconnect(true); keyboard_init(); app_state.current_state = STATE_SCANNING; Serial.begin(115200); }
void loop() { M5Cardputer.update(); KeyEvent key_event = keyboard_process(); switch (app_state.current_state) { case STATE_SCANNING: { uint32_t now = millis(); if (app_state.last_scan_time == 0 || (now - app_state.last_scan_time > 10000)) { app_state.last_scan_time = now; network_count = wifi_scan_networks(wifi_networks, MAX_NETWORKS); app_state.next_state = STATE_LIST; app_state.rssi_history_count = 0; } ui_render_scanning(); break; } case STATE_LIST: { if (key_event.key == KEY_UP && app_state.selected_ap_index > 0) app_state.selected_ap_index--; else if (key_event.key == KEY_DOWN && app_state.selected_ap_index < network_count - 1) app_state.selected_ap_index++; else if (key_event.key == KEY_SELECT) { app_state.next_state = STATE_MEASURING; app_state.rssi_history_count = 0; } else if (key_event.key == KEY_RESCAN) { app_state.next_state = STATE_SCANNING; app_state.last_scan_time = 0; } ui_render_list(wifi_networks, network_count, app_state.selected_ap_index); break; } case STATE_MEASURING: { uint32_t now = millis(); if (now - app_state.last_measure_time > 350) { app_state.last_measure_time = now; int16_t rssi = wifi_measure_rssi(wifi_networks[app_state.selected_ap_index].ssid, wifi_networks[app_state.selected_ap_index].bssid, wifi_networks[app_state.selected_ap_index].channel); if (app_state.rssi_history_count < 30) { app_state.rssi_history[app_state.rssi_history_count++] = rssi; } else { for (int i = 0; i < 29; i++) app_state.rssi_history[i] = app_state.rssi_history[i + 1]; app_state.rssi_history[29] = rssi; } } if (key_event.key == KEY_BACK) app_state.next_state = STATE_LIST; else if (key_event.key == KEY_RESCAN) { app_state.next_state = STATE_SCANNING; app_state.last_scan_time = 0; } ui_render_measuring(wifi_networks[app_state.selected_ap_index], app_state.rssi_history, app_state.rssi_history_count); break; } } if (app_state.next_state != app_state.current_state) app_state.current_state = app_state.next_state; delay(30); }