[env:m5stack_cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    m5unified
    m5gfx
build_flags = 
    -DARDUINO_M5STACK_CARDPUTER